Added a good number of Blue Team tools
fabacab/awesome-cybersecurity-blueteam pull request #28
Opened 2022-08-08 21:03 UTC by D3vil0per

2022-09-09 03:58 UTC, Livelove666 approved these changes

2022-09-12 08:57 UTC, D3vil0p3r commented
Thank you for approving it @Livelove666 Can you merge this PR and also the previous one https://github.com/fabacab/awesome-cybersecurity-blueteam/pull/27 where I fixed some broken link?

Thank you in advance

2022-12-15 22:01 UTC, fabacab requested changes
Largely pretty cool but please submit one tool/line item per pull request.

2022-12-15 22:46 UTC, D3vil0p3r commented on README.md
> +- [BloodHound](https://github.com/BloodHoundAD/BloodHound) - Open source application used for analyzing security of active directory domains. It performs data ingestion from Active Directory domains
Ok, so I don't open a PR for it.

2022-12-15 22:46 UTC, D3vil0p3r commented on README.md
> +- [Blue Team Training Toolkit](https://www.bt3.no/) - Defensive security training software that allows you to create realistic attack scenarios with specific IoCs and evasion techniques. You can crea
Ok. since it reached EOL, I don't open a PR for it.

2022-12-15 22:47 UTC, D3vil0p3r commented on README.md
> +- [ThreatHunting](https://github.com/olafhartong/ThreatHunting) - Splunk app that contains numerous dashboards and over a hundred reports that will help you enable hunting indicators, allowing you to
Ok. I don't create a PR for it.

2022-12-15 22:48 UTC, D3vil0p3r commented
@fabacab Thank you for the answer. According to the comments above, I close this PR since nothing of the tools proposed could be in the scope of the repository.

2022-12-15 22:48 UTC, closed without merging